Repository jedi-studio/verse.db, pull requests merged in 2024-04, with the labels that each got.

#1 Update dependencies, refactor encryption module to secureData, and adjust types/interfaces
  .gitignore
  CHANGELOG.md
  README.md
  SECURITY.md
  package-lock.json
  package.json
  src/adapters/json.adapter.ts
  src/adapters/sql.adapter.ts
  src/adapters/yaml.adapter.ts
  src/core/connect.ts
  src/core/encription.ts
  src/core/secureData.ts
  src/index.ts
  src/types/adapter.ts
  src/types/connect.ts
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: enhancement

#4 "Update file paths for json and yaml adapters, add adapterType to connect class, update search method in yaml adapter"
  src/adapters/json.adapter.ts
  src/adapters/yaml.adapter.ts
  src/core/connect.ts
  tests/versedb.test.ts
Labels: bug

#5 "Add unique ID to new data object in JSON adapter's upsert method"
  src/adapters/json.adapter.ts
Labels: bug, enhancement

#7 Update code-test.yml: change schedule to manual trigger for periodic testing of Verse.db
  .github/workflows/code-test.yml
Labels: enhancement

#8 Change name of CI workflow from "Periodic testing of the Verse.db" to "Testing of the Verse.db"
  .github/workflows/code-test.yml
Labels: enhancement

#10 Update test script in pull request workflow
  .github/workflows/test_pull-request.yaml
Labels: enhancement

#11 Create changlog.yaml
  .github/workflows/changlog.yaml
Labels: documentation

#17 update to latest version and add helpful logging
  README.md
  package-lock.json
  package.json
  src/adapters/export.ts
  src/adapters/json.adapter.ts
  src/adapters/sql.adapter.ts
  src/adapters/yaml.adapter.ts
  src/core/backup.ts
  src/core/connect.ts
  src/core/logger.ts
  src/core/schema.ts
  src/core/secureData.ts
  src/core/watcher.ts
  src/index.ts
  src/lib/colors.ts
  src/types/adapter.ts
  src/types/connect.ts
  src/types/versedb.types.ts
  tests/versedb.test.ts
Labels: enhancement

#18 Fixed some bugs
  src/adapters/sql.adapter.ts
  src/core/connect.ts
  src/core/secureData.ts
  src/core/watcher.ts
Labels: bug, duplicate

#19 Version v2.0.1
  CHANGELOG.md
  README.md
  src/core/secureData.ts
Labels: bug, documentation, enhancement
